package org.nipu.pc.catalog;

import org.springframework.data.mongodb.repository.MongoRepository;
import org.springframework.data.rest.core.annotation.RepositoryRestResource;

/**
 * TODO: This is autogenerated Java-Doc.
 *
 * @author Nikita_Puzankov
 */
@RepositoryRestResource(path = "catalog")
public interface ProductSpecificationRepository extends MongoRepository<ProductSpecification, String> {
}
