package org.nipu.po;

import feign.Logger;
import feign.Request;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

/**
 * TODO: This is autogenerated Java-Doc.
 *
 * @author Nikita_Puzankov
 */
@Configuration
public class FeignConfiguration {

    public static final int FIVE_SECONDS = 300;

    @Bean

    public Logger.Level feignLogger() {

        return Logger.Level.FULL;

    }

    @Bean

    public Request.Options options() {

        return new Request.Options(FIVE_SECONDS, FIVE_SECONDS);

    }

}
